"""second migration

Revision ID: 4abcee699ecb
Revises: 056a8f0cf125
Create Date: 2024-04-22 07:24:58.724933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4abcee699ecb'
down_revision = '056a8f0cf125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('managers', schema=None) as batch_op:
        # Specify the name of the foreign key constraint to be dropped
        batch_op.drop_constraint('department_id', type_='foreignkey')
        batch_op.drop_column('department_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('managers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
