"""Add password_hash column to employees table

Revision ID: 81413d46cf8a
Revises: 08ed37a2b58c
Create Date: 2024-04-22 10:01:22.395901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81413d46cf8a'
down_revision = '08ed37a2b58c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
